// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AdvancedTaskSpecFlow.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("RegistrationFeature")]
    public partial class RegistrationFeatureFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "RegistrationFeature.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "RegistrationFeature", "As a new user, I\'d like to join Mars portal successfully with valid details.\r\nAs " +
                    "a new user, I can\'t join Mars portal with invalid details.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01) A new user register mars portal with valid details")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        [NUnit.Framework.TestCaseAttribute("ada520", "Zhang", "ada520.task@example.com", "123456", "123456", "yes", null)]
        [NUnit.Framework.TestCaseAttribute("ada520", "Zhang", "ada520.task@example.com", "abcdefg", "abcdefg", "yes", null)]
        [NUnit.Framework.TestCaseAttribute("ada520", "Zhang", "ada520.task@example.com", "abc@def", "abc@def", "yes", null)]
        [NUnit.Framework.TestCaseAttribute("ada520", "Zhang", "ada520.task@example.com", "abc@123", "abc@123", "yes", null)]
        public void _01ANewUserRegisterMarsPortalWithValidDetails(string firstName, string lastName, string emailAddress, string password, string confirmPassword, string agreeToTC, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "mytag"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("firstName", firstName);
            argumentsOfScenario.Add("lastName", lastName);
            argumentsOfScenario.Add("emailAddress", emailAddress);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("confirmPassword", confirmPassword);
            argumentsOfScenario.Add("agreeToTC", agreeToTC);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01) A new user register mars portal with valid details", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
 testRunner.Given("Launch Mars portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
 testRunner.When(string.Format("Input valid \'{0}\',\'{1}\',\'{2}\',\'{3}\',\'{4}\',\'{5}\'", firstName, lastName, emailAddress, password, confirmPassword, agreeToTC), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 9
 testRunner.Then("I registered Mars portal successfully", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02) A new user failed to register mars portal with invalid details")]
        [NUnit.Framework.TestCaseAttribute("", "Zhang", "poppy.task@example.com", "123456", "123456", "yes", null)]
        [NUnit.Framework.TestCaseAttribute("Poppy", "", "poppy.task@example.com", "123456", "123456", "yes", null)]
        [NUnit.Framework.TestCaseAttribute("Poppy", "Zhang", "poppy.taskexample.com", "123456", "123456", "yes", null)]
        [NUnit.Framework.TestCaseAttribute("Poppy", "Zhang", "ada.task@example.com", "123456", "123456", "yes", null)]
        [NUnit.Framework.TestCaseAttribute("Poppy", "Zhang", "poppy.task@example.com", "", "123456", "yes", null)]
        [NUnit.Framework.TestCaseAttribute("Poppy", "Zhang", "poppy.task@example.com", "12345", "123456", "yes", null)]
        [NUnit.Framework.TestCaseAttribute("Poppy", "Zhang", "poppy.task@example.com", "123456", "", "yes", null)]
        [NUnit.Framework.TestCaseAttribute("Poppy", "Zhang", "poppy.task@example.com", "123456", "1234567", "yes", null)]
        [NUnit.Framework.TestCaseAttribute("Poppy", "Zhang", "poppy.task@example.com", "123456", "123456", "no", null)]
        public void _02ANewUserFailedToRegisterMarsPortalWithInvalidDetails(string firstName, string lastName, string emailAddress, string password, string confirmPassword, string agreeToTC, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("firstName", firstName);
            argumentsOfScenario.Add("lastName", lastName);
            argumentsOfScenario.Add("emailAddress", emailAddress);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("confirmPassword", confirmPassword);
            argumentsOfScenario.Add("agreeToTC", agreeToTC);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02) A new user failed to register mars portal with invalid details", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 20
 testRunner.Given("Launch Mars portal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 21
 testRunner.When(string.Format("Input invalid \'{0}\',\'{1}\',\'{2}\',\'{3}\',\'{4}\',\'{5}\'", firstName, lastName, emailAddress, password, confirmPassword, agreeToTC), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 22
 testRunner.Then("I registered Mars portal failed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
